export const Messages = {
    FAILED: "Failed to process the request",
    SERVER_ERROR: "Internel server error",
    USER_EXIST: "User already exist",
    USER_BLOCKED: "Your are blocked from Skillhouse",
    USER_NOT_FOUND: "User not found, try to signup",
    JOB_NOT_FOUND: "Job id not found",
    OTP_SENT: "OTP has been sent",
    OTP_RESENT: "OTP has been resent successfully",
    OTP_VERIFIED: "OTP verification successful",
    OTP_EXPIRED: "Your OTP has been expired, resend it",
    INCORRECT_OTP: "The OTP you provided is incorrect",
    NAME_REQUIRED: "Name is required",
    EMAIL_REQUIRED: "Email is required",
    ID_REQUIRED: "User _id is required",
    NO_ACCESS: "Unauthorized Access",
    TOKEN_REQUIRED: "Access denied. No token provided.",
    BLOCKED: "User blocked successfully",
    UNBLOCKED: "User unblocked successfully",
    INVALID_ID: "invalid id, failed to lookup",
    INVALID_TOKEN: "Invalid authentication token.",
    INVALID_BIO: "Bio should contains 100 - 600 characters",
    INVALID_FILE_TYPE: "Only jpeg, jpg, webp and png files allowed",
    INVALID_ROLE: "Invalid role",   
    INVALID_NAME: "Please enter a valid name (A - Z)",
    INVALID_EMAIL: "Please enter a valid email",
    INVALID_REQUEST: "Invalid Request",
    INVALID_CREDENTIALS: "Invalid password or email",
    INVALID_GOOGLE_TOKEN: "Invalid google id token",
    INVALID_DATE_RANGE: "End date must be after start date",
    INVALID_START_DATE: "Start date cannot be in the past",
    INVALID_AMOUNT: "Invalid amount",
    PASSWORD_RESET_SUCCESS: "Your password has been reset successfully",
    PASSWORD_RESET_FAILED: "Password reset failed, try again later",
    PASSWORD_REQUIRED: "Password is required",
    PASSWORD_LENGTH: "Your password must be at least 8 characters long",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    PROFILE_UPDATED: "Profile updated successfully",
    PROFILE_PICTURE_UPDATE: "Profile picture updated successfully",
    NO_FILE: "No file uploaded",
    LOGIN_SUCCESS: "Login successful",
    LOGOUT_SUCCESS: "Logout successful",
    SIGNUP_SUCCESS: "Signup successful",
    CATEGORY_NOT_FOUND: "Category not found",
    CATEGORY_EXIST: "Category already exists",
    SKILLS_NOT_FOUND: "Skills not found",
    SKILLS_EXIST: "Skill already exists",
    CATEGORY_LISTED: "Category listed successfully",
    CATEGORY_UNLISTED: "Category unlisted successfully",
    SKILLS_LISTED: "Skills listed successfully",
    SKILLS_UNLISTED: "Skils unlisted successfully",
    ERROR_FETCHING_PROFILE: "Failed to fetch profile",
    ERROR_UPDATING_PROFILE: "Error updating proifle",
    REQUIRED_ALL: "All feilds are required",
    ACCESS_DENIED: "You are not authorized to access this job.",
    FREELANCER_ID_REQUIRED: "Freelancer ID is required",
    ALREADY_APPLIED: "You have already applied for this job",
    JOB_RATE_LIMIT: "Job rate must be greater than zero",
    JOB_DESCRIPTION_REQUIRED: "Job description cannot be empty",
    JOB_TITLE_REQUIRED: "Job title cannot be empty",
    JOB_ID_REQUIRED: "Job ID is required",
    JOB_UPDATED: "Job has been updated",
    JOB_APPLICATION_SUCCESS: "Job application submitted successfully",
    JOB_CLOSED: "Job is closed, or hired someone",
    JOB_APPLICATION_REQUIRED: "Job application id required or missing",
    JOB_APPLICATION_CANCELLED: "Job application request has been cancelled",
    MISSING_PARAMETERS: "Missing required parameters. Please provide all necessary fields.",
    CONTRACT_CREATE: "Job contract has been created",
    CONTRACT_CANCELLED: "Your job contract has been cancelled",
    CONTRACT_APPROVE: "Contract has been approved",
    CONTRACT_REJECTED: "Contract has been rejected",
    CONTRACT_STATUS_UPDATED: "Contract status changed",
    CONTRACT_STATUS_UPDATE_FAILED: "Contract status changing has failed",
    CONTRACT_NOT_FOUND: "Contract not found or existed",
    CONTRACT_EXIST: "Contract is already exist",
    NO_JOB_FOUND: "Job not found",
    FREELANCER_NOT_APPLIED: "Freelancers not applied",
    CURRENT_PASSWORD_WRONG: "Current password is incorrect.",
    PASSWORD_NOT_MATCH: "New password and confirm password do not match.",
    GOOGLE_ACCOUNT: "This account is linked with Google. Cannot reset password.",
    RESET_LINK_SENT: "Password reset link has been sent to your email.",
    RESET_TOKEN_INVALID: "Reset token is invalid or has expired.",
    RESET_TOKEN_REQUIRED: "Reset toeken is required",
    FUND_RELEASED: "Fund has been released",
    REFUND_PROCESSED: "Refund has been processed",
    REFUND_NOT_ALLOWED: "Refund not allowed for a finished contract",
    PAYMENT_REQUEST_PROCESSED: "Freelancer payment release request has recieved",
    ESCROW_NOT_FOUND: "Escrow not found for the contract id",
    PAYMENT_REQUEST_NOT_VALID: "Payment request not valid",
    WORK_NOT_COMPLETED: "You can request release only after work completion.",
    FUNDS_ADDED: "Fund has been added to user wallet",
    FUND_RELEASE_REQUEST: "Fund release requested successfully.",
    ALREADY_FUNDED: "Funds have already been released for this contract.",
    ALREADY_REFUNDED: "Refund has already given",
    REVIEW_CREATED: "Review created successfully",
    ADMIN_REGISTER_FORBIDDEN: "You are not authorized to register as admin.",
}